kind: pipeline
name: default

steps:
- name: restore-cache
  image: appleboy/drone-sftp-cache
  volumes:
    - name: cache_gradle
      path: /tmp/cache_gradle
    - name: cache_gradlewrapper
      path: /tmp/gradlewrapper
    - name: cache_androidavd
      path: /tmp/androidavd
  settings:
    restore: true
    mount:
      - /tmp/cache_gradle
      - /tmp/cache_gradlewrapper
      - /tmp/cache_androidavd
    server: 
      from_secret: ssh_server
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password  
    path: /docker/gitea/drone-data/cache

- name: build
  image: mingc/android-build-box:1.7.0
  volumes:
    - name: cache_gradle
      path: /root/.gradle/caches
    - name: cache_gradlewrapper
      path: /root/.gradle/wrapper
    - name: cache_androidavd
      path: /opt/android-sdk/.android/avd
  commands:
    - if [ ! $(command -v file) ]; then apt-get update ; apt-get -y install file ; fi
    - bash ./gradlew assemble
    - tar -czf ${DRONE_REPO_NAME}_${DRONE_COMMIT_SHA}_build.tar.gz app/build

- name: store-artifacts
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_server
    user: 
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    source:
      - ./*build.tar.gz
    target: 
      - /volume1/docker/gitea/drone-data/artifacts

- name: rebuild-cache
  image: appleboy/drone-sftp-cache
  volumes:
    - name: cache_gradle
      path: /tmp/cache_gradle
    - name: cache_gradlewrapper
      path: /tmp/gradlewrapper
    - name: cache_androidavd
      path: /tmp/androidavd
  settings:
    rebuild: true
    mount:
      - cache_gradle
      - cache_gradlewrapper
      - cache_androidavd
    server:
      from_secret: ssh_server
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password  
    path: /docker/gitea/drone-data/cache

volumes:
  - name: cache_gradle
    temp: {}
  - name: cache_gradlewrapper
    temp: {}
  - name: cache_androidavd
    temp: {}