kind: pipeline
name: android-build

steps:
- name: restore-cache
  image: appleboy/drone-sftp-cache
  volumes:
    - name: cache_gradle
      path: /tmp/cache_gradle
    - name: cache_gradlewrapper
      path: /tmp/gradlewrapper
    - name: cache_androidavd
      path: /tmp/androidavd
  settings:
    mount:
      - /tmp/cache_gradle
      - /tmp/cache_gradlewrapper
      - /tmp/cache_androidavd
    server:
      from_secret: ssh_server
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    path: /docker/gitea/drone-data/cache
    restore: true

- name: androidkeys
  image: obiwan:8008/drone-plugin-androidkeys
  settings:
    key_base64:
      from_secret: key_base64

- name: myname
  image: alpine
  commands:
    - sed -i "/\s*versionName.*/s/\"$/-sletteng-${DRONE_COMMIT_SHA:0:5}\"/" ./app/build.gradle

- name: build
  image: mingc/android-build-box:1.9.0
  volumes:
    - name: cache_gradle
      path: /root/.gradle/caches
    - name: cache_gradlewrapper
      path: /root/.gradle/wrapper
    - name: cache_androidavd
      path: /opt/android-sdk/.android/avd
  commands:
    - bash ./gradlew assemble

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_api_key
    base_url: https://git.home.sletteng.org
    files:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/apk/debug/app-debug.apk
    checksum:
      - md5
      - sha1
    draft: true
  when:
    ref:
    - refs/heads/feature-*
    - refs/tags/v*

- name: prepare-artifacts
  image: alpine
  commands:
    - tar -czf ${DRONE_REPO_NAME}_${DRONE_COMMIT_SHA}_build.tar.gz app/build
  when:
    status:
    - success
    - failure

- name: store-artifacts
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_server
    user:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    source:
      - ./*build.tar.gz
    target: 
      - /volume1/docker/gitea/drone-data/artifacts
  when:
    status:
    - success
    - failure

- name: rebuild-cache
  image: appleboy/drone-sftp-cache
  volumes:
    - name: cache_gradle
      path: /tmp/cache_gradle
    - name: cache_gradlewrapper
      path: /tmp/gradlewrapper
    - name: cache_androidavd
      path: /tmp/androidavd
  settings:
    mount:
      - /tmp/cache_gradle
      - /tmp/cache_gradlewrapper
      - /tmp/cache_androidavd
    server:
      from_secret: ssh_server
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    path:
      from_secret: ssh_cache_path
    rebuild: true
  when:
    status:
    - success
    - failure

volumes:
  - name: cache_gradle
    temp: {}
  - name: cache_gradlewrapper
    temp: {}
  - name: cache_androidavd
    temp: {}
